### ISSUE TITLE
ColorColumns Not Working Inside of Tmux

### ISSUE THREAD

**Issue by parmort** [skielbasa/vim-material-monokai#1]
For whatever reason, I cannot get colorcolumns to display inside of Tmux. All terminal variables are set to 'xterm-256color' and the ColorColumn highlighting is set to `ctermbg=15`, which should render the color column white. I have also set the color column to 81.

**Comment by skielbasa** [comment]
Since you closed the issue, did you find out what the problem was?

**Comment by parmort** [comment]
I did. I'm writing a pull request now
