### ISSUE TITLE
Airline Error Bar Changing Color

### ISSUE THREAD

**Issue by tommyknows** [skielbasa/vim-material-monokai#5]
Hi,

I opened an issue at the vim-airline repo that uses your theme. I assumed it might be a bug in the airline-config here, so I wanted to link it here as well :-)

https://github.com/vim-airline/vim-airline/issues/1682

**Comment by skielbasa** [comment]
Looked into it, it is a theme bug. I should have a fix out later today.

**Comment by skielbasa** [comment]
The fix is out. Also, thanks for pointing this out. While trying to fix it, I learned more about how Airline themes work and was able to add a theme feature I've wanted to have since the beginning.
