### ISSUE TITLE
Different Colors

### ISSUE THREAD

**Issue by tobyjamesthomas** [skielbasa/vim-material-monokai#7]
Hey there! I love your theme and use it on all my machines. I got a new MacBook, and I tried setting my vim colours to material-monokai again, but I'm getting different colours and I can't figure out why.

<img width="1655" alt="Screen Shot 2019-09-07 at 3 53 33 PM" src="https://user-images.githubusercontent.com/14275937/64479651-e38d7700-d187-11e9-90f7-7dc4f6f57050.png">

Do you know why this is happening? I have material-monokai.vim in my ~/.vim/colors and am using the same .vimrc that I use with all my machines.

Thanks

**Comment by skielbasa** [comment]
Does your terminal support true colors and if so is support enabled? Are
you running from inside a tmux session?

**Comment by tobyjamesthomas** [comment]
Thanks for the quick reply, @skielbasa! I'm using iTerm2 and the report terminal type is xterm-256color. Is there anything else I need to do to enable true colors? I'm not running from inside a tmux session, but it also displays the wrong colors (same as above).

**Comment by skielbasa** [comment]
That should be it; you also need it enabled in your .vimrc, but you said
its the same one you're using on other machines so it it shouldn't be that.
I'm kinda stumped unfortunately. The reason I asked about tmux is that it
can mess with true color support. Iterm is what I use as well. Is iterm set
to xterm-256color under Report Terminal Type?

**Comment by tobyjamesthomas** [comment]
Yes, it is. No worries, I'll let you know if I figure it out! Thanks for your help!

**Comment by tobyjamesthomas** [comment]
Problem solved! Had to do with the version of vim I was using. It was a new MacBook, so I forgot to brew install vim and was using the preinstalled version instead. The pictures below show the version numbers. Thanks again and great theme!

<img width="353" alt="Screen Shot 2019-09-13 at 3 26 14 PM" src="https://user-images.githubusercontent.com/14275937/64889697-e088ff80-d63b-11e9-97cc-e8477ad5a3d6.png">
<img width="336" alt="Screen Shot 2019-09-13 at 3 31 58 PM" src="https://user-images.githubusercontent.com/14275937/64889698-e088ff80-d63b-11e9-9380-441fb6448132.png">
